services:
  - type: web
    name: piazza-web
    runtime: ruby
    plan: free
    numInstances: 1
    buildCommand: ./bin/render-build.sh
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: bundle exec puma -C config/deploy/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: piazza-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
databases:
  - name: piazza-db
    plan: free
    # postgresMajorVersion: 14
